name: Charts Blocks
type: module
description: Create Charts blocks without the need for Views.
core_version_requirement: ^10.3 || ^11
package: Charts
dependencies:
  - drupal:charts

# Information added by Drupal.org packaging script on 2025-12-13
version: '5.1.10'
project: 'charts'
datestamp: 1765584160
