views.argument_default.current_user_profile:
  type: mapping
  label: 'Current user profile'
  mapping:
    type:
      type: string
      label: 'Profile type'

views.relationship.profile_relationship:
  type: views_relationship
  label: 'Profile relationship'
  mapping:
    profile_type:
      type: string
      label: 'Profile type'
