
existing_values_autocomplete_widget.autocomplete:
  path: '/existing-values/autocomplete/{field_name}/{count}/{entity_type_id}'
  defaults:
    _controller: '\Drupal\existing_values_autocomplete_widget\Controller\AutocompleteController::handleAutocomplete'
    _title: 'Handle Autocomplete of text fields with existing values'
    _format: json
    field_name: NULL
    count: 15
    entity_type_id: NULL
  requirements:
    _permission: 'access content'
