name: 'Chart.js Charts'
type: module
description: 'Charts module integration with Chart.js.'
package: Charts
core_version_requirement: ^9.2 || ^10
dependencies:
  - 'charts:charts'

# Information added by Drupal.org packaging script on 2022-09-19
version: '5.0.3'
project: 'charts'
datestamp: 1663595980
