name: Charts
type: module
description: 'A charting API for Drupal that provides chart elements and integration with Views.'
package: Charts
core_version_requirement: ^10.3 || ^11
configure: charts.settings

# Information added by Drupal.org packaging script on 2025-12-13
version: '5.1.10'
project: 'charts'
datestamp: 1765584160
